#+TODO: TODO WORK DONE

* bin/bin/cleaning-time [0/1]
** TODO Interactive mode
The script prints all input devices from =xinput= command with the ids. Then
asks the user to "Which input devices you going to clean?" and the user gives a
list of the ids of devices. This way is more user friendly than edit script
variables after every restart of pc.
* bin/bin/tre [0/1]
** TODO Export excluded directory variable
Use =TRE_EXCLUDED= variable for exclude directories
* bin/bin/pomodoro [0/5]
** TODO Input validation
Throw an error message when the user gives incorrect arguments.
** TODO Print more information
Print messages like:
- [ ] =[TIME] Pomodoro started/finished=
- [ ] =[TIME] Short break started/finished=
- [ ] =[TIME] Long break started/finished=
- [ ] =Total Pomodoro Count:[NUMBER]=
** TODO Run a shell command after or before any step of the pomodoro
For example, May I need to pause music when started short or long break. Or may
write an information about pomodoro session to a text file.
** TODO Play a sound when any step started :maybe:
Plays notification sound to take care of.
** TODO Countdown :maybe:
Countdown animation.

* Script Ideas
** TODO font-manager
install, remove and upgrade fonts.
